### ISSUE TITLE
Dependencies updates

### ISSUE THREAD

**Issue by ioreskovic** [miwurster/spring-data-influxdb#11]
Hi,

Is there a plan to update dependency versions anytime soon?

**Comment by miwurster** [comment]
Fixed with 46ffa43c381ddd6258c17fba1b219ad30dce036c.

By the way, if there are no breaking changes in the `influxdb-java` library you can just add the dependency to your project's `pom.xml` with the appropriate version you wanna use. e.g.:
```xml
<dependency>
  <groupId>org.influxdb</groupId>
  <artifactId>influxdb-java</artifactId>
  <version>2.8</version>
</dependency>
```

Anyhow, the verson `1.7` will be available thru Maven Central any time soon.

Cheers
Michael
